### PR TITLE
Fixed error when releasing vertex or line and fixed missing tabs.css

### PR DESCRIPTION
**Pull request by cbosse-skwirrel**

### CODE REVIEW

**Comment by keithrfung** [comment]
This seems to still be an open issue with `react-planner`. Is there a reason this hasn't been merged?

**Comment by JaccoGoris** [comment]
Can we merge this in? The project is unusable as a dependency right now because it does not compile

**Comment by danilosalvati** [comment]
I will have a look to it in the next days

**Comment by danilosalvati** [comment]
For the next pull requests I would prefer to use develop as the base branch. Anyway for this one I will proceed to merge into the project and fix issues with develop branch.

Thanks for your contribution :smile:

**Pull request merged**
