### PR TITLE
fixed missing fa icon in panel-guides

### PR DESCRIPTION
**Pull request by JaccoGoris**
Regarding #166 
I've set my PR to merge into develop, since I read that in the previous PR comments, but maybe it would be helpful to put that in the readme?
I can add it in this PR if you want.

I didn't know how to build the libs etc so I am just pushing my sourcecode changes, hope that's the correct flow?

### CODE REVIEW

**Comment by JaccoGoris** [comment]
I updated the built files to be able to test it in my main project already, so I figured I can push these, since the other PR had them too.

**Comment by JaccoGoris** [comment]
Sorry about the large amount of lines changed, apparently prettier was still on and reformatted the whole file

**Comment by danilosalvati** [comment]
> I updated the built files to be able to test it in my main project already, so I figured I can push these, since the other PR had them too.

No problem with pushing the build files. Anyway, when we release a new version the build command is launched automatically so it's the same :smile:

**Comment by danilosalvati** [comment]
> Regarding #166
> I've set my PR to merge into develop, since I read that in the previous PR comments, but maybe it would be helpful to put that in the readme?
> I can add it in this PR if you want.

No I prefer to keep this pull requests only for fixes... I will update the readme with contributions informations later

**Comment by danilosalvati** [comment]
Excellent work :+1:

**Comment by JaccoGoris** [comment]
Thanks!

**Pull request merged**
